config/routes.rb
Rails.application.routes.draw do
 
  resources :events
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get '/calendar', to: 'calendars#index'

  resources :availabilities
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/availability.rb
class Availability < ApplicationRecord
    
    
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController
  def index
  end

  def new
    @availability = Availability.new
  end

  def create
    @availability = Availability.new(availability_params)

    charge(availability_params)
  end

  def edit
  end

  private

  def charge(availability)
    
    availability["available"].each  do |a|
      av = Availability.new
      av.day_of_week = a[0]
      av.start_time =  a[2,6]
      av.teacher = [*1..10].sample
      av.available = true
      av.save
    end
            # if available.save
            #     flash[:notice] = "Your order was created with success!"
            # else
            #     flash[:alert] = available.errors.full_messages.join(', ')
            # end
  end
    


  def availability_params
     params.require(:availability).permit(available:[])
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
    def index
        @events = Availability.where(teacher:6).where(available:true)      
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:description, :start_date, :end_date, :hour, :user, :available)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def index
     # @categories = Category.all
  
    end
  
    def home
    end
  
    def search
    
    end
  
    def calendar
      #params[:start_date] ||= Date.current.to_s
  
      #start_date = Date.parse(params[:start_date])
      #first_of_month = (start_date - 1.month).beginning_of_month
      #end_of_month = (start_date + 1.month).end_of_month
  
      #@orders = Order.where("seller_id = ? AND status = ? ANd due_date BETWEEN ? AND ? ",
       #         current_user.id,
        #        Order.statuses[:inprogress],
         #       first_of_month,
          #      end_of_month)
    end
  
    def plans
      #@plans = Stripe::Plan.list(product: 'prod_FcR2K4KQfHMA1b')
  
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/availability_helper.rb
module AvailabilityHelper
end

app/helpers/availabity_helper.rb
module AvailabityHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/availabilities/create.html.erb
<h1>Availability#create</h1>
<p>Find me in app/views/availability/create.html.erb</p>

app/views/availabilities/edit.html.erb
<h1>Availability#edit</h1>
<p>Find me in app/views/availability/edit.html.erb</p>

app/views/availabilities/index.html.erb
<h1>Availability#index</h1>
<p>Find me in app/views/availability/index.html.erb</p>

app/views/calendars/index.html.erb
<%= stylesheet_link_tag "/assets/core/main.css" %>
<%= stylesheet_link_tag "/assets/daygrid/main.css" %>
<%= stylesheet_link_tag "/assets/list/main.css" %>
<%= stylesheet_link_tag "/assets/timegrid/main.css" %>

<section class="section">
  <div class="container m-t-20">
    <div id="calendar">

    </div>
  </div>
</section>
<style>
.fc-past {
  background-color: #bfbfbf;
}
</style>

<script type="text/javascript">
    ev = <%= raw @events.to_json %>
    console.log(ev)

    function showEvents(ev){
      return ev.map(function(o){
      
        stime = window.moment(o.start_time).utc().format('hh:mm:ss')
        eTime = window.moment(o.start_time).add(50,'minutes').utc().format('hh:mm')
      // console.log(o.start_time.split('T')[1].substring(0,8))
      // console.log(window.moment(o.start_time).isValid())
        return{
          startRecur: new Date(),
          daysOfWeek: [o.day_of_week],
          startTime: stime,
          endTime: eTime,
          title:  'Available',
          color: 'green'
         }
      })
    }
    console.log(showEvents(ev))
    $(function() {
        var calendarEl = document.getElementById('calendar');

        var calendar = new Calendar(calendarEl, {
            
            
            header: {
                left: 'prev,next',
                center: 'title',
                right: 'dayGridMonth,timeGridWeek,listMonth'
            },

                    plugins: [DayGridPlugin, ListPlugin,TimeGridPlugin],
            events:  showEvents(ev) ,
            defaultView: 'dayGridMonth'
        });

         calendar.render();
    })
</script>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>

  <div class="field">
    <%= form.label :hour %>
    <%= form.time_select :hour %>
  </div>

  <div class="field">
    <%= form.label :user %>
    <%= form.number_field :user %>
  </div>

  <div class="field">
    <%= form.label :available %>
    <%= form.check_box :available %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Hour</th>
      <th>User</th>
      <th>Available</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.description %></td>
        <td><%= event.start_date %></td>
        <td><%= event.end_date %></td>
        <td><%= event.hour %></td>
        <td><%= event.user %></td>
        <td><%= event.available %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @event.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @event.end_date %>
</p>

<p>
  <strong>Hour:</strong>
  <%= @event.hour %>
</p>

<p>
  <strong>User:</strong>
  <%= @event.user %>
</p>

<p>
  <strong>Available:</strong>
  <%= @event.available %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Booking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
Index